import {
  ArrowRight,
  Command, 
  FileText,
  Fingerprint,
  Layers,
  LayoutDashboard,
  Lock,
  LucideIcon,
  Mail,
  Moon,
  Settings,
  SunMedium,
  Upload,
  User,
  Database,
  Shield,
  Sparkles,
  Wallet,
  Loader2,
  Check,
  Plus as Add,
  Clock,
  Trash,
  Download,
  Info,
  LogIn,
  Link,
  ArrowLeft,
  AlertCircle,
  AlertTriangle,
  ExternalLink,
  Share2,
  Search,
  File,
} from "lucide-react"

export type IconKeys = keyof typeof icons

type IconsType = {
  [key in IconKeys]: LucideIcon
}

const icons = {
  logo: Command,
  arrowRight: ArrowRight,
  dashboard: LayoutDashboard,
  document: FileText,
  fingerprint: Fingerprint,
  lock: Lock,
  moon: Moon,
  settings: Settings,
  sun: SunMedium,
  upload: Upload,
  user: User,
  vault: Layers,
  database: Database,
  shield: Shield,
  sparkles: Sparkles,
  wallet: Wallet,
  spinner: Loader2,
  mail: Mail,
  check: Check,
  add: Add,
  clock: Clock,
  trash: Trash,
  download: Download,
  info: Info,
  login: LogIn,
  link: Link,
  arrowLeft: ArrowLeft,
  alertCircle: AlertCircle,
  externalLink: ExternalLink,
  share2: Share2,
  search: Search,
  file: File,
  warning: AlertTriangle,
}

export const Icons: IconsType = icons
